### ISSUE TITLE
Add checkbox tool

### ISSUE THREAD

**Issue by chuckh** [miztroh/wysiwyg-e#43]
Add checkbox tool like:

- [ ] Item one
- [x] Item two 
- [ ] Item three 

Possible use: 
```
<input type="checkbox" value="Bike"> I have a bike<br>
<input type="checkbox" value="Car" checked> I have a car<br>
```

**Comment by miztroh** [comment]
@chuckh Care to submit a PR for this?

**Comment by chuckh** [comment]
@miztroh I will give it a try.

**Comment by chuckh** [comment]
## Screenshot of Doc
![image](https://cloud.githubusercontent.com/assets/19915/13011094/f50e6390-d159-11e5-86cd-0132146fe47c.png)

## Screenshot of Demo
![image](https://cloud.githubusercontent.com/assets/19915/13011130/255f2a70-d15a-11e5-8e0f-3285fc21932d.png)

**Comment by chuckh** [comment]
I am working on this now.  Got inserting Checkbox working ok. 

#### Todo for adding Checkbox Tool

- [x] Inserting Checkbox
- [ ] Remove Checkbox
- [ ] On Enter Key add another checkbox
- [ ] Handle changing code on checking/unchecking Checkbox

**Comment by miztroh** [comment]
@chuckh Any news here?

**Comment by chuckh** [comment]
@miztroh have not had a chance to get back to this the last few weeks. I have been off working on a time sensitive client project. I should be able to get back to it next week. Sorry for the delay. My current status is:

- [x] Inserting Checkbox
- [x] Remove Checkbox (just need to backspace to remove)
- [ ] On Enter Key add another checkbox 
- [x] Handle changing code on checking/unchecking Checkbox

**Comment by miztroh** [comment]
@chuckh Any update here?

**Comment by miztroh** [comment]
Closing due to age.  Create a new one if / when a PR is ready.
